### ISSUE TITLE
schedule.ex を最低限の骨組みだけの状態にする

### ISSUE THREAD

**Issue by kuroda** [ysaito8015/np#1]
Section 5.2 で schedule.ex を作った後、次のように書き換える手順を加えてください。 

```elixir
defmodule NanoPlanner.Schedule do
  import Ecto.Query, warn: false
  alias NanoPlanner.Repo

  alias NanoPlanner.Schedule.PlanItem
end
```

文章の書き方（案）:

* Phoenixが生成した schedule.ex には基本的なCRUD操作のための関数群とドキュメントのサンプルが含まれている。
* 読者の皆さんが自分のアプリケーションを開発する際には、これらの関数群とドキュメントを利用してもいい。
* しかし、本シリーズでは説明の都合と紙幅の節約のため、いったん schedule.ex を最低限の骨組みだけの状態にすることにした。

**Comment by ysaito8015** [comment]
done
